name: msbingo
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - astroquery
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.9
  - scipy
